name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Lint with flake8
        #run: |
         # flake8 src tests api --max-line-length=120
      - name: Set PYTHONPATH to include src/
        run: export PYTHONPATH="${PYTHONPATH}:./src"

      - name: Run tests with pytest
        run: |
          pytest tests/

  docker-build-push:
    needs: build-test-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "satishaddanki" # ${{ secrets.DOCKER_USERNAME }}
          password: "Paddu123$" # ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: docker build -t satishaddanki/housing-api:latest .
      
      - name: Push Docker image to Docker Hub
        run: docker push satishaddanki/housing-api:latest
